version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: pontia_vector_db
    command: "./qdrant --config-path /config/config.yaml"
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_data_pontia:/qdrant/storage
      - ./qdrant_config/config.yaml:/config/config.yaml
    restart: always